# Generated by Django 4.1.2 on 2022-10-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_bicho', '0002_jogobicho_resultado_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogobicho',
            name='resultado_hora',
        ),
    ]
