# Generated by Django 4.1.2 on 2022-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_bicho', '0004_alter_jogobicho_bicho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome:')),
                ('telefone', models.CharField(max_length=200, verbose_name='Telefone:')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail:')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço:')),
                ('tipo_aposta', models.CharField(max_length=200, verbose_name='Tipo de aposta:')),
                ('num_conta', models.CharField(max_length=200, verbose_name='Número da Conta:')),
            ],
        ),
    ]
