# Generated by Django 4.1.2 on 2022-10-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MegaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_1', models.IntegerField()),
                ('num_2', models.IntegerField()),
                ('num_3', models.IntegerField()),
                ('num_4', models.IntegerField()),
                ('num_5', models.IntegerField()),
                ('num_6', models.IntegerField()),
            ],
        ),
    ]
