# Generated by Django 4.1.2 on 2022-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_sena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megasena',
            name='num_1',
            field=models.IntegerField(verbose_name='Número 01:'),
        ),
        migrations.AlterField(
            model_name='megasena',
            name='num_2',
            field=models.IntegerField(verbose_name='Número 02:'),
        ),
        migrations.AlterField(
            model_name='megasena',
            name='num_3',
            field=models.IntegerField(verbose_name='Número 03:'),
        ),
        migrations.AlterField(
            model_name='megasena',
            name='num_4',
            field=models.IntegerField(verbose_name='Número 04:'),
        ),
        migrations.AlterField(
            model_name='megasena',
            name='num_5',
            field=models.IntegerField(verbose_name='Número 05:'),
        ),
        migrations.AlterField(
            model_name='megasena',
            name='num_6',
            field=models.IntegerField(verbose_name='Número 06:'),
        ),
    ]
